#!/bin/bash
#
# generate-readme.sh
# Generate README.md file for this repository
#
# Brandon Amos
# https://github.com/bamos/dotfiles/blob/master/generate-readme.sh

set -x -e +H
cd "$(dirname "$0")"

cat>README.md<<EOF
<!--

This README is auto-generated with generate-readme.sh
Please add changes there.

-->

# About
This repository contains configuration files I use on Linux system
which have been inspired by the rest of the dotfiles community.
This \`README\` has been automatically generated by
[generate-readme.sh][generate-readme.sh] on $(date).

[generate-readme.sh]: https://github.com/samtron1412/dotfiles/blob/master/generate-readme.sh

# Installation

Clone this repo with git's \`--recursive\` flag to obtain all the submodules.
Run [bootstrap.sh][bootstrap.sh] to symlink all of the dotfiles in this repo
to the home directory and install vim plugins.

[bootstrap.sh]: https://github.com/samtron1412/dotfiles/blob/master/bootstrap.sh

# What programs do these configure?
<!-- TODO: Make this easier to maintain. -->
+ Misc Linux config: [.xinitrc](/.xinitrc), [.Xresources](/.Xresources)
+ [aria2](https://github.com/tatsuhiro-t/aria2): [.aria2](/.aria2)
+ [cmus](https://cmus.github.io/): [.cmus](/.cmus)
+ [conky](https://wiki.archlinux.org/index.php/Conky): [.conkyrc](/.conkyrc)
+ [emacs](https://www.gnu.org/software/emacs/): [.emacs.d](/.emacs.d)
+ [git](https://git-scm.com/): [.gitignore_global](/.gitignore_global)
+ [GNU aspell](http://aspell.net): [.aspell.en.pws](/.aspell.en.pws)
+ [GPG](https://www.gnupg.org): [.gnupg](/.gnupg)
+ [i3wm](https://i3wm.org/): [.i3](/.i3)
+ [ispell](https://www.gnu.org/software/ispell/): [.ispell_english](/.ispell_english)
+ [mpv](http://mpv.io): [.mpv](/.mpv)
+ [mutt](http://www.mutt.org): [.mutt](/.mutt) and [.muttrc](/.muttrc)
+ [sbt](http://www.scala-sbt.org): [.sbt](/.sbt)
+ [screen](https://www.gnu.org/software/screen/): [.screenrc](/.screenrc)
+ [tmux](https://tmux.github.io/): [.tmux.conf](/.tmux.conf)
+ [vim](http://www.vim.org/): [.vim](/.vim)
+ [wget](https://www.gnu.org/software/wget/): [.wgetrc](/.wgetrc)
+ [xmonad](http://xmonad.org): [.xmonad](/.xmonad)
+ [zsh](http://www.zsh.org): [.zshrc](/.zshrc), [.zshenv](/.zshenv),
  [.zsh-custom](/.zsh-custom), and [.funcs](/.funcs).

# References

- [Medium - Managing your dotfiles](https://medium.com/@webprolific/managing-your-dotfiles-7d2725297304#.cvp4c33bc)
- [Managing your dotfiles](http://www.anishathalye.com/2014/08/03/managing-your-dotfiles/)
- [vcs-home](https://vcs-home.branchable.com/)
- [Subverting your homedir, or keeping your life in svn](http://joeyh.name/svnhome/)
- [dotfiles GitHub Pages](https://dotfiles.github.io/)
- [dotfiles resources](https://github.com/webpro/awesome-dotfiles)
- [bamos/dotfiles](https://github.com/bamos/dotfiles)

# License
[MIT License](https://github.com/samtron1412/dotfiles/blob/master/LICENSE).
EOF
